Fix curl error (6)
Use fedora:34 as a base image instead of fedora:latest until
this issue is fixed:
https://bugzilla.redhat.com/show_bug.cgi?id=1988199

Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedora
project.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Error: error building at STEP "RUN /usr/local/bin/toolbox_install_basic.sh": error while running runtime: exit status 1