install latest version of delve
Because of
+ go install github.com/go-delve/delve/cmd/dlv@v1.9.0
go: downloading github.com/go-delve/delve v1.9.0
go: github.com/go-delve/delve/cmd/dlv@v1.9.0: github.com/go-delve/delve@v1.9.0 requires
	gopkg.in/yaml.v2@v2.4.0: unrecognized import path "gopkg.in/yaml.v2": reading https://gopkg.in/yaml.v2?go-get=1: 502 Bad Gateway
	server response: Cannot obtain refs from GitHub: error reading from GitHub: net/http: request canceled (Client.Timeout exceeded while reading body)
Error: error building at STEP "RUN /usr/local/bin/toolbox_install_golang.sh": error while running runtime: exit status 1